# Generated by Django 4.2.13 on 2024-06-23 02:03

from django.db import migrations, models
import record_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=16, validators=[record_manager.models.validate_phone_number])),
                ('Location', models.CharField(max_length=255)),
                ('Hobby', models.CharField(max_length=255)),
            ],
        ),
    ]
